language: scala
scala:
 - 2.12.4
 - 2.11.12
jdk: oraclejdk8
cache:
  directories:
   - ~/.ivy2
   - ~/.sbt
script:
  - "sbt ++${TRAVIS_SCALA_VERSION} \";clean;dependencyUpdates;scalafmt::test;compile\""
  - "sbt ++${TRAVIS_SCALA_VERSION} \";clean;coverage;test;coverageReport;coverageAggregate\""
after_success:
  - bash <(curl -s https://codecov.io/bash)